version: "3.9"

services:
  controller:
    build: .
    command: ./controller
    container_name: controller

  node1:
    build: .
    environment:
      - NODE_ID=1
    container_name: node1

  node2:
    build: .
    environment:
      - NODE_ID=2
    container_name: node2